all:
	cd unit_test && make $@
	cd chaos-max && make $@

cooja02:
	cd unit_test && make $@
	cd static && make $@
	cd dynamic && make $@

cooja06:
	cd unit_test && make $@
	cd static && make $@
	cd dynamic && make $@

cooja32:
	cd unit_test && make $@
	cd static && make $@
	cd dynamic && make $@
	
clean:
	cd unit_test && make $@
	cd static && make $@
	cd dynamic && make $@	