all:	
	cd 01-rx-test && make $@
	cd 02-tx-test && make $@
	cd 03-slotted-test && make $@
	cd 04-slotted-multi-test && make $@
	cd 05-scheduler-2apps-test && make $@

cooja02:
	cd 01-rx-test && make $@
	cd 02-tx-test && make $@
	cd 03-slotted-test && make $@
	cd 04-slotted-multi-test && make $@
	cd 05-scheduler-2apps-test && make $@

cooja06:
	cd 01-rx-test && make $@
	cd 02-tx-test && make $@
	cd 03-slotted-test && make $@
	cd 04-slotted-multi-test && make $@
	cd 05-scheduler-2apps-test && make $@

cooja32:
	cd 01-rx-test && make $@
	cd 02-tx-test && make $@
	cd 03-slotted-test && make $@
	cd 04-slotted-multi-test && make $@
	cd 05-scheduler-2apps-test && make $@

clean:
	cd 01-rx-test && make $@
	cd 02-tx-test && make $@
	cd 03-slotted-test && make $@
	cd 04-slotted-multi-test && make $@
	cd 05-scheduler-2apps-test && make $@
		